name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pytest playwright pytest-playwright pytest-html
          python -m playwright install chromium --with-deps

      - name: Create cred.json file
        run: |
          mkdir -p data
          cat > data/cred.json <<EOF
          {
            "user_credentials": [
              {
                "user_email": "${{ secrets.USER1_EMAIL }}",
                "user_password": "${{ secrets.USER1_PASSWORD }}"
              },
              {
                "user_email": "${{ secrets.USER2_EMAIL }}",
                "user_password": "${{ secrets.USER2_PASSWORD }}"
              }
            ]
          }
          EOF

      - name: Run tests
        run: |
          xvfb-run python -m pytest pytestDir/test_pw.py --html=report.html --self-contained-html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report.html
          if-no-files-found: error

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2   # change if your region is different

      - name: Upload report to S3
        run: |
          aws s3 cp report.html s3:///playwright-qa-reports-dwija/report.html

      - name: Print report URL
        run: |
          echo "Report URL: https:///playwright-qa-reports-dwija.s3.amazonaws.com/report.html"